/**
 * The film. This is the site's primary visual language.
 *
 * Every plate was generated by Higgsfield from a Blender collector frame shot on
 * the camera its chapter uses, so a cut lands on the framing the 3D scene was
 * blocked for. Chapters 1 through 8 are additionally anchored to one hero vessel
 * reference, so the same ship leaves Visakhapatnam, works the Bay and comes
 * home, rather than three different boats.
 *
 * A plate holds its whole chapter. It rises just before the chapter starts and
 * stays up; because plates paint in chapter order, the next one rising covers
 * the last, and that is the dissolve. Only a plate with no successor releases
 * the frame, which hands the ending back to WebGL for the globe.
 */
export type PlateMove = 'in' | 'out' | 'left' | 'right' | 'up'

export interface CinematicPlate {
  /** chapter id this plate belongs to */
  chapter: string
  /** still frame, always present, also used as the video poster */
  still: string
  /** motion clip, when one was generated */
  video?: string
  /** the slow camera move held across the chapter */
  move: PlateMove
  /** object-position, to bias the crop away from something that must stay in */
  focus?: string
  /** fade out at the end, for a plate the next chapter does not cover */
  release?: boolean
  /** short caption for accessibility */
  alt: string
}

const S = '/assets/media/higgsfield/stills'
const V = '/assets/media/higgsfield/video'

export const cinematicPlates: CinematicPlate[] = [
  {
    chapter: 'ch01-opening-port',
    still: `${S}/ch01-opening-port.jpg`,
    video: `${V}/ch01-opening-port.mp4`,
    move: 'in',
    alt: 'A steel fishing vessel alongside the quay at Visakhapatnam, gantry cranes and container stacks behind her',
  },
  {
    chapter: 'ch02-boarding',
    still: `${S}/ch02-boarding.jpg`,
    video: `${V}/ch02-boarding.mp4`,
    move: 'left',
    alt: 'Crew boarding the vessel with nets, rope and insulated crates',
  },
  {
    chapter: 'ch03-compass',
    still: `${S}/ch03-compass.jpg`,
    video: `${V}/ch03-compass.mp4`,
    move: 'right',
    alt: 'The vessel underway, leaving the harbour mouth for open water',
  },
  {
    chapter: 'ch04-into-the-bay',
    still: `${S}/ch04-into-the-bay.jpg`,
    video: `${V}/ch04-into-the-bay.mp4`,
    move: 'up',
    alt: 'Seen from directly overhead, the vessel running alone in the Bay of Bengal with a white wake astern',
  },
  {
    chapter: 'ch05-nets',
    still: `${S}/ch05-crew-hauling.jpg`,
    video: `${V}/ch05-crew-hauling.mp4`,
    move: 'in',
    alt: 'The crew haul a full net of mixed catch over the rail',
  },
  {
    chapter: 'ch06-swordfish-and-tuna',
    still: `${S}/ch06-catch.jpg`,
    video: `${V}/ch06-catch.mp4`,
    move: 'in',
    // bias the crop left so the swordfish bill never leaves the frame
    focus: '36% 50%',
    alt: 'Swordfish and tuna resting on crushed ice in a clean deck bin',
  },
  {
    chapter: 'ch07-onboard-cold-storage',
    still: `${S}/ch07-chilled-hold.jpg`,
    video: `${V}/ch07-chilled-hold.mp4`,
    move: 'in',
    alt: 'The catch stowed in clean onboard chilled storage',
  },
  {
    chapter: 'ch08-return-to-port',
    still: `${S}/ch08-return-to-port.jpg`,
    video: `${V}/ch08-return-to-port.mp4`,
    move: 'in',
    alt: 'The vessel inbound to Visakhapatnam with the container port behind her',
  },
  {
    chapter: 'ch09-cold-chain-transfer',
    still: `${S}/ch09-transfer.jpg`,
    video: `${V}/ch09-transfer.mp4`,
    move: 'left',
    alt: 'Cold-chain transfer on the quay at Visakhapatnam',
  },
  {
    chapter: 'ch10-processing-arrival',
    still: `${S}/ch10-processing.jpg`,
    video: `${V}/ch10-processing.mp4`,
    move: 'in',
    alt: 'The processing hall, stainless tables and workers in clean protective clothing',
  },
  {
    chapter: 'ch11-cutting',
    still: `${S}/ch11-cutting.jpg`,
    video: `${V}/ch11-cutting.mp4`,
    move: 'in',
    alt: 'Workers in protective clothing laying trimmed tuna loin portions onto a stainless tray',
  },
  {
    chapter: 'ch12-pond-origin',
    still: `${S}/ch12-ponds.jpg`,
    video: `${V}/ch12-ponds.mp4`,
    move: 'up',
    alt: 'Aquaculture ponds along the Andhra coast seen from the air',
  },
  {
    chapter: 'ch13-product-forms',
    still: `${S}/ch13-product-forms.jpg`,
    move: 'in',
    alt: 'Export shrimp product forms presented on stainless trays',
  },
  {
    chapter: 'ch14-grading',
    still: `${S}/ch14-grading.jpg`,
    video: `${V}/ch14-grading.mp4`,
    move: 'left',
    alt: 'The grading conveyor separating shrimp and fish portions into size grades',
  },
  {
    chapter: 'ch15-qc-and-residue-testing',
    still: `${S}/ch15-qc.jpg`,
    video: `${V}/ch15-qc.mp4`,
    move: 'in',
    alt: 'A quality control inspector working in the residue testing laboratory',
  },
  {
    chapter: 'ch16-freezing-and-glazing',
    still: `${S}/ch16-freezing.jpg`,
    video: `${V}/ch16-freezing.mp4`,
    move: 'in',
    alt: 'Frost and glazing mist in the freezing tunnel',
  },
  {
    chapter: 'ch17-packing-and-cold-storage',
    still: `${S}/ch17-cold-storage.jpg`,
    video: `${V}/ch17-cold-storage.mp4`,
    move: 'in',
    alt: 'A long aisle of pallet racking inside the cold store',
  },
  {
    chapter: 'ch18-export-documents',
    still: `${S}/ch18-documents.jpg`,
    move: 'in',
    alt: 'A squared stack of clean export paperwork resting on a stainless documentation desk',
  },
  {
    chapter: 'ch19-reefer-containers',
    still: `${S}/ch19-reefer.jpg`,
    video: `${V}/ch19-reefer.mp4`,
    move: 'right',
    alt: 'A reefer container loaded with sealed seafood cartons',
  },
  {
    chapter: 'ch20-container-vessel',
    still: `${S}/ch20-container-vessel.jpg`,
    video: `${V}/ch20-container-vessel.mp4`,
    move: 'in',
    // the globe is the last word, so this plate releases the frame back to WebGL
    release: true,
    alt: 'A container vessel leaving Visakhapatnam in deep blue water',
  },
]

export const plateFor = (chapterId: string) =>
  cinematicPlates.find((p) => p.chapter === chapterId)
