/**
 * The film, one entry per chapter.
 *
 * `still` is the opening frame: it paints instantly, holds while the scrub strip
 * streams in, and is the whole picture for a reader on reduced motion. The
 * frames themselves live under public/assets/frames and are indexed by
 * frames.json; src/components/FilmStrip.tsx draws them.
 *
 * Every plate was generated by Higgsfield from a Blender collector frame shot on
 * the camera its chapter uses, so a cut lands on the framing the 3D scene was
 * blocked for. Chapters 1 through 8 are additionally anchored to one hero vessel
 * reference, so the same ship leaves Visakhapatnam, works the Bay and comes
 * home, rather than three different boats.
 *
 */
export interface CinematicPlate {
  /** chapter id this plate belongs to */
  chapter: string
  /** still frame, always present, also used as the video poster */
  still: string
  /** short caption for accessibility */
  alt: string
}

const S = '/assets/media/higgsfield/stills'

export const cinematicPlates: CinematicPlate[] = [
  {
    chapter: 'ch01-opening-port',
    still: `${S}/ch01-opening-port.jpg`,
    alt: 'A steel fishing vessel alongside the quay at Visakhapatnam, gantry cranes and container stacks behind her',
  },
  {
    chapter: 'ch02-boarding',
    still: `${S}/ch02-boarding.jpg`,
    alt: 'Crew boarding the vessel with nets, rope and insulated crates',
  },
  {
    chapter: 'ch03-compass',
    still: `${S}/ch03-compass.jpg`,
    alt: 'The vessel underway, leaving the harbour mouth for open water',
  },
  {
    chapter: 'ch04-into-the-bay',
    still: `${S}/ch04-into-the-bay.jpg`,
    alt: 'Seen from directly overhead, the vessel running alone in the Bay of Bengal with a white wake astern',
  },
  {
    chapter: 'ch05-nets',
    still: `${S}/ch05-crew-hauling.jpg`,
    alt: 'The crew haul a full net of mixed catch over the rail',
  },
  {
    chapter: 'ch06-swordfish-and-tuna',
    still: `${S}/ch06-catch.jpg`,
    alt: 'Swordfish and tuna resting on crushed ice in a clean deck bin',
  },
  {
    chapter: 'ch07-onboard-cold-storage',
    still: `${S}/ch07-chilled-hold.jpg`,
    alt: 'The catch stowed in clean onboard chilled storage',
  },
  {
    chapter: 'ch08-return-to-port',
    still: `${S}/ch08-return-to-port.jpg`,
    alt: 'The vessel inbound to Visakhapatnam with the container port behind her',
  },
  {
    chapter: 'ch09-cold-chain-transfer',
    still: `${S}/ch09-transfer.jpg`,
    alt: 'Cold-chain transfer on the quay at Visakhapatnam',
  },
  {
    chapter: 'ch10-processing-arrival',
    still: `${S}/ch10-processing.jpg`,
    alt: 'The processing hall, stainless tables and workers in clean protective clothing',
  },
  {
    chapter: 'ch11-cutting',
    still: `${S}/ch11-cutting.jpg`,
    alt: 'Workers in protective clothing laying trimmed tuna loin portions onto a stainless tray',
  },
  {
    chapter: 'ch12-pond-origin',
    still: `${S}/ch12-ponds.jpg`,
    alt: 'Aquaculture ponds along the Andhra coast seen from the air',
  },
  {
    chapter: 'ch13-product-forms',
    still: `${S}/ch13-product-forms.jpg`,
    alt: 'Export shrimp product forms presented on stainless trays',
  },
  {
    chapter: 'ch14-grading',
    still: `${S}/ch14-grading.jpg`,
    alt: 'The grading conveyor separating shrimp and fish portions into size grades',
  },
  {
    chapter: 'ch15-qc-and-residue-testing',
    still: `${S}/ch15-qc.jpg`,
    alt: 'A quality control inspector working in the residue testing laboratory',
  },
  {
    chapter: 'ch16-freezing-and-glazing',
    still: `${S}/ch16-freezing.jpg`,
    alt: 'Frost and glazing mist in the freezing tunnel',
  },
  {
    chapter: 'ch17-packing-and-cold-storage',
    still: `${S}/ch17-cold-storage.jpg`,
    alt: 'A long aisle of pallet racking inside the cold store',
  },
  {
    chapter: 'ch18-export-documents',
    still: `${S}/ch18-documents.jpg`,
    alt: 'A squared stack of clean export paperwork resting on a stainless documentation desk',
  },
  {
    chapter: 'ch19-reefer-containers',
    still: `${S}/ch19-reefer.jpg`,
    alt: 'A reefer container loaded with sealed seafood cartons',
  },
  {
    chapter: 'ch20-container-vessel',
    still: `${S}/ch20-container-vessel.jpg`,
    alt: 'A container vessel leaving Visakhapatnam in deep blue water',
  },
]

export const plateFor = (chapterId: string) =>
  cinematicPlates.find((p) => p.chapter === chapterId)
